sprite $ing [64x63/16z] {
hLVPaiGW21mF3lSb__-tQmuJYJYIEFsmjLELHcmRn6Nf8frONY09pB6VHaWgvjZM2EahvjYZ2Cc4ENOlGdg4EVOjWkbx1kg5iF63npd-ny4atqLM-4R1LhuQ
uFX1U83bkhG3lLiHgCSFxW38j9r4hQBaVyedjSxHkNu0iVsBxwySmIa0hWEalplVXV81UOr_9QYldsK-Dg_J8u_ukuQDTes-Wj-aY1fRkBXsptRAK6jOrlUR
BVnTspt0pMLGQxZBTr2s_GLEt_dNWSUo0-pvN-Mpy26SSYdrj_BREhdE75TMoLYf_mvGQ5WovaZMrWQD3xS0vjR8yUR3fxWqn7S1JWqhkvZpPw7XO_t8WwQX
zVnMd-3THbt_j8ZbuBtKKFTlv-oluXdKJxtlkdwZqB1Vl_Nz8Be4gxtttZ-Q--LX_-hn3vs6_RF3D_TldM-_Fn8l2jzyVua6_EB-J3-vlvUtyyEFvfTE01xD
JzydG8B1_3QOFxV6pUT_pVmu6c09E6PmWloNclqC1s2Cx94ZKc1IQcuuVsT-BWF8o2P4mmJ_X6zuFnG-XTnwqFG2aVeXPoSZ9GG8-Fu1ay-10jcUKFgx8KRR
yaOZ__Rzzmy0
}
